export enum Times {
  PSG = "PSG",
  REAL_MADRID = "Real Madrid",
  ARSENAL = "Arsenal",
  CITY = "Manchester City",
  BARCELONA = "Barcelona",
}

export const jogadoresPorTime = {
  [Times.PSG]: [
    "Maurício Edson de Souza",
    "Anderson Nascimento Santos",
    "Douglas F Santos",
    "Ian Henrique",
    "Diogo Ediardo",
    "Gustavo de jesus",
    "Pablo Oliveira",
    "Renatinho jeremias",
    "Leonardo da Silva",
    "Matheus Pastorzão",
  ],
  [Times.REAL_MADRID]: [
    "Felipe Paulino",
    "George Silva",
    "Vinicius Augusto",
    "Silas Santos",
    "Gabriel Santos",
    "Carlos Eduardo",
    "Marcilio Souza",
    "Matheus Assis",
    "Matheus colantuano",
    "Kewin",
  ],
  [Times.ARSENAL]: [
    "Silas Lira",
    "Dener Vieira de Souza",
    "Tiago Santos Nogueira",
    "André Aparecido P de Souza",
    "Gustavo Silva",
    "Arthur Costa Ribeiro ",
    "Eder Loredo",
    "Otávio Neri",
    "Charlyes",
    "Leonardo Barbosa",
  ],
  [Times.CITY]: [
    "Luiz Carlos da Silva Francisco",
    "William Ferreira",
    "Douglas Santos",
    "Alexander lino",
    "Nathan Henrique",
    "Rafael Bento Ferreira",
    "Rodrigada",
    "Mateus Jackson",
    "Vini Franca",
    "Danilo da Silva Rocha",
  ],
  [Times.BARCELONA]: [
    "Gabriel Santos Fonseca",
    "Paulo Victor da Silva",
    "Diego Evangelista Gonçalves",
    "Victor Prudencio",
    "Victor Henrique",
    "Emanuel Medeiros",
    "Yan haikimi",
    "João Vitor Fernandes de Souza",
    "Gilberlanio",
    "Carlos Eduardo Gonçalves da Silva",
  ],
};
